version: "3.9"

services:
  db:
    image: postgres:15
    container_name: backend-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: dan # change
      POSTGRES_PASSWORD: backend # change
      POSTGRES_DB: backend # chgange
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
